name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd /home/ubuntu/SnapCart

            echo "Pulling latest code..."
            git fetch origin main
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm install
            echo "Removing stale Next.js build lock..."
            rm -f .next/lock

            echo "Building Next.js application..."
            NODE_OPTIONS="--max-old-space-size=600" npm run build

            echo "Restarting PM2..."
            pm2 restart snapcart

            echo "Deployment completed successfully!"
